# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
<<<<<<< HEAD
  username: postgresql
  password:
=======
>>>>>>> 06db2904bcca9c8a3857be579054a2f5ba3409a2

#development:
  #<<: *default
  #database: db/development.sqlite3

#test:
  #<<: *default
  #database: db/test.sqlite3

#production:
  #<<: *default
  #database: db/production.sqlite3

development:
  adapter: sqlite3
  encoding: utf8
  database: health_tracking
  pool: 5
<<<<<<< HEAD
  username: sqlite3
  password:

test: &TEST
  adapter: sqlite3
  encoding: utf8
  database: project_test
  pool: 5
  username: sqlite3
  password:
=======

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
>>>>>>> 06db2904bcca9c8a3857be579054a2f5ba3409a2

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
<<<<<<< HEAD
  username: postgresql
  password:
=======
>>>>>>> 06db2904bcca9c8a3857be579054a2f5ba3409a2
  
# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
